parameters:
  name: 'GenerateBuildArtifacts'

jobs:
- job: ${{ parameters.name }}
  dependsOn:
    - Linux
    - OSX
    - Windows
  condition: succeeded()
  variables:
    python_version: 3.7
    os_name:  Linux
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 25
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Python for test execution'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements-dev.txt
      python -m pip install .
    displayName: 'Install requirements'

  - script: |
      inv build
    displayName: Generate sdist archives

  - task: PublishBuildArtifacts@1
    displayName: Store sdist archives
    inputs:
      PathtoPublish: dist/
      ArtifactType: container
      TargetPath: ""
      ArtifactName: sdist

  - bash: |
      inv docs
    displayName: 'Generate Keyword Documentation'

  - task: PublishBuildArtifacts@1
    displayName: Store Keyword Documentation
    inputs:
      PathtoPublish: docs/keywords.html
      ArtifactType: container
      TargetPath: ""
      ArtifactName: documentation
