trigger:
  batch: true
  paths:
    exclude:
    - docs/
jobs:
- template: azure/job_template.yml
  parameters:
    name: 'OSX'
    vmImage: 'macOS-10.13'
- template: azure/job_template.yml
  parameters:
    name: 'Windows'
    vmImage: 'VS2017-Win2016'
    robotPrefix: 'PATH=~/bin:${PATH}'
- template: azure/job_template.yml
  parameters:
    name: 'Linux'
    vmImage: 'ubuntu-16.04'
    robotPrefix: 'PATH=~/bin:${PATH} xvfb-run --auto-servernum --server-args="-screen 1, 1600x900x24"'
- template: azure/artifacts.yml
  parameters:
    name: 'GenerateBuildArtifacts'

